# Basic workflow to build latex and publish
name: Build and Publish .pdf and .png

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build PDF
      - name: install xelatex
        run: sudo apt-get install texlive-xetex

      # Build PDF
      - name: install fonts
        run: tlmgr install sourcesanspro

      # Build PDF
      - name: make pdf
        run: make resume-public.pdf

      # convert to png
      - name: Run a multi-line script
        run: make pngs
