# Basic workflow to build latex and publish
name: Build and Publish .pdf and .png

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      RELEASE_FILENAME: resume
      BUILD_DIR: build
      INPUT_FLAGS: -density 150
      OUTPUT_FLAGS: -background white -flatten -quality 100
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create Build Dir
        run: mkdir $BUILD_DIR

      # install reqs
      - name: Compile Latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tex/resume-public.tex
          latexmk_use_xelatex: true
          args: -output-directory=${{ BUILD_DIR }} -interaction=nonstopmode

      - name: Create .png
        run: |
          convert $(INPUT_FLAGS) $(BUILD_DIR)/resume-public.pdf $(OUTPUT_FLAGS) $(BUILD_DIR)/resume-public.png

      - name: Rename
        run: |
          mv $BUILD_DIR/resume-public.pdf $BUILD_DIR/$RELEASE_FILENAME.pdf
          mv $BUILD_DIR/resume-public.png $BUILD_DIR/$RELEASE_FILENAME.png

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          body: Latest version of public resume
          files: |
            $BUILD_DIR/resume.pdf
            $BUILD_DIR/resume.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
