# Basic workflow to build latex and publish
name: Build and Publish .pdf and .png

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PUBLIC: ${{ secrets.PUBLIC }}

    steps:
      - uses: actions/checkout@v2

      - name: Install Imagemagick
        run: |
          sudo apt update
          sudo apt install -y imagemagick
          sudo apt install -y ghostscript
          sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml

      - name: Show PUBLIC
        run:
          echo $PUBLIC

      # install reqs
      - name: Compile Latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tex/resume-public.tex
          latexmk_use_xelatex: true

      - name: Create .png
        run: |
          convert -density 150 resume-public.pdf -background white -flatten -quality 100 resume-public.png

      - name: Rename
        run: |
          mv resume-public.pdf resume-latest-mp.pdf
          mv resume-public.png resume-latest-mp.png

      - name: Upload Release Asset
        if: ${{ !env.ACT }}
        uses: softprops/action-gh-release@v1
        with:
          name: latest
          tag: latest
          body: Latest version of public resume
          files: |
            resume-latest-mp.pdf
            resume-latest-mp.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
